all:
  children:
    storage:
      hosts:
        k8sstorage:
          ansible_host: 192.168.0.41
    k8smaster:
      hosts:
        k8smaster1:
          ansible_host: 1.1.1.1
        k8smaster2:
          ansible_host: 2.2.2.2
    teleport:
      hosts:
        teleportproxy:
          ansible_host: 192.168.0.41