---
- hosts: storage
  tasks:
    - name: hostvars
      ansible.builtin.debug:
        var: hostvars["{{item}}"].ansible_host
      with_inventory_hostnames:
        - all:!storage
    - name: set-facts | make nfs exports var
      set_fact:
        nfs_server_exports: "{{ nfs_server_exports|default([]) +  export_host_config }}"
      vars:
        export_host_config:
            - export:
              access:
                - hostname: "{{ hostvars[item].ansible_host }}"
                  options:
                    - 'rw'
                    - 'sync'
                    - 'no_subtree_check'
                    - 'no_root_squash'
              mode: "u=rwx,g=rx,o=rx"
              path: '/opt/k8sstor'
      with_inventory_hostnames:
        - all:!storage

#    - name: Print return information from the previous task
#      ansible.builtin.debug:
#        var: nfs_exports_k8s
#    - name: Print return information from the previous task
#      ansible.builtin.debug:
#        var: nfs_server_exports

- hosts: storage
  roles:
    - role: roles/ansible-nfs-server
  tasks: